apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: raft-cluster
spec:
  serviceName: "raft-peers"
  replicas: 3
  selector:
    matchLabels:
      app: raft-node
  template:
    metadata:
      labels:
        app: raft-node
    spec:
      containers:
        - name: raft-node
          image: ghcr.io/amodkala/raft:main
          ports:
            - containerPort: 8080
              name: raft
          env:
          - name: POD_NAME
            valueFrom:
            fieldRef:
              fieldPath: metadata.name
          - name: RAFT_SERVICE_NAME
            value: "raft-peers.default.svc.cluster.local"
